# Generated by Django 5.1 on 2024-08-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='wing_span',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
